name: wakala
description: We exchange is an app accelate mobile transer betwwen peers
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.0
  flutter_neumorphic: ^3.2.0
  firebase_auth: ^3.3.4
  cloud_firestore: ^3.1.5
  firebase_core: ^1.10.6
  geolocator: ^8.0.1
  google_maps_flutter: ^2.1.1
  url_launcher: ^6.0.17
  flutter_ringtone_player: ^3.1.1
  firebase_messaging: ^11.2.4
  provider: ^6.0.2
  smooth_star_rating_null_safety: ^1.0.4+2
  google_maps_widget: ^0.0.9



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/mno/
    - assets/images/banks/
    - assets/images/delivery/
    - assets/images/
    - assets/sound/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/poppins/Poppins-Regular.ttf
        - asset: assets/poppins/Poppins-Bold.ttf
